### ISSUE TITLE
Redirects to installation page after initial install

### ISSUE THREAD

**Issue by bregoh** [smartstore/Smartstore#1037]
I used smartstore docker container on Azure, connected to Postgres DB. After the first installation and database write, a successful message appears and asked to click for redirection or wait for automatic redirection. However, when I wait or click that, I return back to the installation page and it continues in the same cycle

Service: Azure web app service
Container Registry: Azure container registry
DB: Postgresql

Also note that I have neither updated nor modified the docker image, I pulled from smartstore and pushed to azure. No article online can tell me why this happens. 

Its urgent. Thanks!!!

**Comment by zihniartar** [comment]
The reason for this is that there is no volume for the "Tenants" folder.

For my own tests, I put the tenants folder of Docker containers in a local folder (outside of Docker, on my PC), like this:

```
Volumes:
      - "./Tenants/:/app/App_Data/Tenants:rw"
```

I also place the volume for the PostgreSQL database in a local folder:

```
volumes:
       - postgres-db:/data/postgres

volumes
  postgres-db:
    Driver: local
```

If I do the same in Azure, Smartstore behaves as you described. The installation accepts all entries and runs through. After the restart, the installation page appears again.

However, if I create extra volumes for the tenant folder and the PostgreSQL-DB, Smartstore is installed correctly and runs.
I have never used the Azure Registry, probably you create the volumes via startup command.

Here is my complete Docker Compose file:

```
version: "3.4"
services:
  web-pg:
    image: ghcr.io/smartstore/smartstore-linux:latest
    container_name: web-pg
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - App_Data:/app/App_Data/Tenants 
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: SomeSecretPassword
      PGDATA: /data/postgres
    restart: unless-stopped 
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
  App_Data: 
```
